CREATE DATABASE IF NOT EXISTS developers
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;


CREATE TABLE IF NOT EXISTS DEVELOPERS (
  ID_DEVELOPERS INT(11) NOT NULL AUTO_INCREMENT,
  NAME_DEVELOPERS VARCHAR(80) NOT NULL ,
  SURNAME_DEVELOPERS VARCHAR(100) NOT NULL ,
  CITY VARCHAR(80),


  PRIMARY KEY (ID_DEVELOPERS)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PROJECTS (
  ID_PROJECTS INT(11) NOT NULL AUTO_INCREMENT,
  PROJECTS VARCHAR(80) NOT NULL ,

  PRIMARY KEY (ID_PROJECTS)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DEVELOPERS_PROJECTS(
  ID_DEVELOPERS INT(11) NOT NULL ,
  ID_PROJECTS  INT(11) NOT NULL ,

  PRIMARY KEY (ID_DEVELOPERS , ID_PROJECTS),
  FOREIGN KEY (ID_DEVELOPERS) REFERENCES DEVELOPERS (ID_DEVELOPERS),
  FOREIGN KEY (ID_PROJECTS)  REFERENCES DEVELOPERS (ID_PROJECTS)


)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS COMPANY (
  ID_COMPANY INT (11) NOT NULL AUTO_INCREMENT,
  COMPANY VARCHAR(100) NOT NULL ,

  PRIMARY KEY (ID_COMPANY)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS COMPANY_PROJECTS(
  ID_COMPANY INT (11) NOT NULL ,
  ID_PROJECTS INT (11) NOT NULL ,

  PRIMARY KEY (ID_COMPANY , ID_PROJECTS),
  FOREIGN KEY (ID_COMPANY) REFERENCES COMPANY (ID_COMPANY),
  FOREIGN KEY (ID_PROJECTS) REFERENCES COMPANY (ID_PROJECTS)

)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS SKILLS (
  ID_SKILLS INT (11) NOT NULL AUTO_INCREMENT,
  SKILLS VARCHAR(70) NOT NULL ,


  PRIMARY KEY (ID_SKILLS)
)

  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS DEVELOPERS_SKILLS (
  ID_DEVELOPERS INT (11) NOT NULL ,
  ID_SKILLS INT (11) NOT NULL ,

  PRIMARY KEY (ID_DEVELOPERS, ID_SKILLS),
  FOREIGN KEY (ID_DEVELOPERS) REFERENCES DEVELOPERS (ID_DEVELOPERS),
  FOREIGN KEY (ID_SKILLS) REFERENCES DEVELOPERS (ID_SKILLS)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
  ID_CUSTOMERS INT (11) NOT NULL AUTO_INCREMENT,
  NAME_CUSTOMERS VARCHAR(70) NOT NULL ,
  SURNAME_CUSTOMERS VARCHAR(90) NOT NULL ,

  PRIMARY KEY (ID_CUSTOMERS)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CUSTOMERS_PROJECTS(
  ID_CUSTOMERS INT(11) NOT NULL ,
  ID_PROJECTS INT (11) NOT NULL ,

  PRIMARY KEY (ID_CUSTOMERS , ID_PROJECTS),
  FOREIGN KEY (ID_CUSTOMERS) REFERENCES CUSTOMERS (ID_CUSTOMERS),
  FOREIGN KEY (ID_PROJECTS) REFERENCES CUSTOMERS (ID_PROJECTS)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS COMPANY_DEVELOPERS (
  ID_COMPANY INT (11) NOT NULL ,
  ID_DEVELOPERS INT (11) NOT NULL ,

  PRIMARY KEY (ID_COMPANY , ID_DEVELOPERS),
  FOREIGN KEY (ID_COMPANY) REFERENCES COMPANY (ID_COMPANY),
  FOREIGN KEY (ID_DEVELOPERS) REFERENCES COMPANY (ID_DEVELOPERS)
)
  ENGINE InnoDB;